apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default  # Ensure this matches the namespace where your pods are running
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
